#!/bin/bash

# Install Nginx (if not already installed)
apt-get update
apt-get install -y nginx

# check etc/nginx/sites-availble for the config files

# Configure Nginx to listen on port 80
echo "server {
    listen 80 default_server;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to set the new config
service nginx restart

echo "Nginx is now port 80."
