#!/usr/bin/env bash
# Script does the same thing as ./0-nginx_likes_port_80
apt-get update
apt-get install -y nginx
echo "server { listen 80 default_server; server_name _; location / { root /usr/share/nginx/html; index index.html index.htm; } }" > /etc/nginx/sites-available/default
service nginx stop
