#!/usr/bin/env bash
#displays the content of the file `/etc/passwd`
#only displays the:
#username
#user id
#Home directory path for the user
while IFS= read -r LINE;
do
	echo "$LINE" | cut -d':' -f1,3,6
done < /etc/passwd
