#!/usr/bin/env bash
while IFS=: read -r username _ uid  password groupid info home shell; do
	# Displaying user information in the specified format
	echo "The user $username is part of the $groupid gang, lives in $home, and rides $shell."
	echo "$uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
