#!/usr/bin/env bash
# Default settings for all hosts
Host *
	# Use the private key for authentication
        IdentityFile ~/.ssh/school

	# Disable password authentication
	PasswordAuthentication no
